# Generated by Django 3.2.12 on 2023-10-18 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Finances.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
