# Generated by Django 3.2.13 on 2022-07-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=4, unique=True, verbose_name='Code')),
                ('number', models.CharField(blank=True, max_length=4, unique=True, verbose_name='Number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
