# Generated by Django 3.2.13 on 2022-07-19 16:46

import sys

from django.db import migrations
from django.conf import settings
from core.Utils.migration import load_fixture


def load_fixtures(apps, schema_editor):
    if settings.TEST_MODE or 'test' in sys.argv:
        return

    Currency = apps.get_model('Currency', 'Currency')

    qs = Currency.objects.all()
    if not qs.exists():
        load_fixture(apps, 'core/Currency/fixtures/currency_data.json', 'Currency.Currency')
        print('[+] Load Currency fixtures')
    else:
        raise ValueError('Currency already exists!')


class Migration(migrations.Migration):

    dependencies = [
        ('Currency', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures)
    ]
