# Generated by Django 3.2.12 on 2023-09-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0003_shoppinglistproduct_user'),
    ]

    operations = [
    ]
