# Generated by Django 3.2.12 on 2023-09-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0005_alter_shoppinglistproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
