# Generated by Django 3.2.12 on 2023-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0006_alter_shoppinglistproduct_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
