# Generated by Django 3.2.12 on 2023-09-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0007_shoppinglistproduct_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistproduct',
            old_name='is_active',
            new_name='is_checked',
        ),
    ]
