# Generated by Django 3.2.12 on 2023-10-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0008_rename_is_active_shoppinglistproduct_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistproduct',
            name='units',
            field=models.CharField(choices=[('gramm', 'Gr'), ('kilogram', 'KG'), ('milliter', 'ML'), ('liter', 'L'), ('Units', 'Units')], db_index=True, max_length=16),
        ),
    ]
