# Generated by Django 3.2.12 on 2023-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
