# Generated by Django 3.2.12 on 2023-09-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0003_fridgetype_create_on_user_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridgeproduct',
            old_name='storage',
            new_name='fridge',
        ),
    ]
