# Generated by Django 3.2.12 on 2023-09-24 19:58

from django.db import migrations


def fridgeproduct_assign_user(apps, schema):
    FridgeProduct = apps.get_model("Fridge", "FridgeProduct")
    for product in FridgeProduct.objects.select_related('fridge__user').all():
        product.user = product.fridge.user
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('Fridge', '0005_fridgeproduct_user'),
    ]

    operations = [
        migrations.RunPython(fridgeproduct_assign_user)
    ]
