# Generated by Django 3.2.12 on 2023-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0008_alter_fridgeproduct_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeproduct',
            name='notified_as',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
