# Generated by Django 3.2.12 on 2023-09-24 17:53

from django.db import migrations

MESSAGE = """Greetings, {{first_name}} {{last_name}}!\n
Please clicking on the link below to reset your password: {{ url }}"""

MESSAGE_HTML = """Greetings, {{first_name}} {{last_name}}!<br>
Please clicking on the link below to reset your password: <a href="{{ url }}" type="button" target="_blank">Link</a><br>
Or, if the link in not active, just paste it to your browser: {{ url }}"""


def add_registration_activate_email(apps, schema):
    slug = 'forgot-password-reset-email'
    Notification = apps.get_model('Notifications', 'Notification')
    notification, created = Notification.objects.get_or_create(
        slug=slug,
        defaults={
            'name': 'Email for user to reset password',
            'description': 'Email for user to reset password',
            'message': MESSAGE,
            'message_html': MESSAGE_HTML,
            'subject': 'Reset password',
        }
    )
    if created:
        print(f'Notification {slug} created')
    else:
        print(f'Notification {slug} already exists')


class Migration(migrations.Migration):
    dependencies = [
        ('Notifications', '0002_add_registration_activate_email'),
    ]

    operations = [
        migrations.RunPython(add_registration_activate_email)
    ]
