# Generated by Django 3.2.12 on 2023-09-24 17:53

from django.db import migrations


def add_product_will_expire(apps, schema):
    MESSAGE = """Greetings, {{first_name}} {{last_name}}! Product {{ product_label }} will expire {{ date_str }}."""

    slug = 'product-will-expire'
    Notification = apps.get_model('Notifications', 'Notification')
    notification, created = Notification.objects.get_or_create(
        slug=slug,
        defaults={
            'name': 'Email for user to notify that product will expire',
            'description': 'Email for user to notify that product will expire',
            'message': MESSAGE,
            'message_html': MESSAGE,
            'subject': 'Product will expire',
        }
    )
    if created:
        print(f'Notification {slug} created')
    else:
        print(f'Notification {slug} already exists')


def add_product_expired(apps, schema):
    MESSAGE = """Greetings, {{first_name}} {{last_name}}! Product {{ product_label }} is expired."""

    slug = 'product-expired'
    Notification = apps.get_model('Notifications', 'Notification')
    notification, created = Notification.objects.get_or_create(
        slug=slug,
        defaults={
            'name': 'Email for user to notify that product is expired',
            'description': 'Email for user to notify that product is expired',
            'message': MESSAGE,
            'message_html': MESSAGE,
            'subject': 'Product is expired',
        }
    )
    if created:
        print(f'Notification {slug} created')
    else:
        print(f'Notification {slug} already exists')


class Migration(migrations.Migration):
    dependencies = [
        ('Notifications', '0003_add_forgot_password_reset_email'),
    ]

    operations = [
        migrations.RunPython(add_product_will_expire),
        migrations.RunPython(add_product_expired),
    ]
