# Generated by Django 3.2.12 on 2023-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='name',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='is_default',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='termsofuse',
            name='is_default',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
