# Generated by Django 3.2.12 on 2023-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licence', '0002_default_licences'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenceversion',
            name='is_default',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
