# Generated by Django 3.2.12 on 2023-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licence', '0003_default_licences'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='name',
            field=models.CharField(default='Licence name', max_length=128),
        ),
    ]
