# Generated by Django 3.2.12 on 2023-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licence', '0004_licence_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceversion',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='licenceversion',
            name='name',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
